name: 'Manual Deploy to Staging'
on: workflow_dispatch

jobs:
  manual-deploy-staging:
    uses: ./.github/workflows/deploy-app-workflow.yml
    with:
      environment: STAGING
      branch: ${{ github.ref }}
    secrets:
      ssh_host: ${{ secrets.STAGING_HOST }}
      ssh_user: ${{ secrets.USERNAME }}
      ssh_key_ed25519: ${{ secrets.STAGING_KEY_ED25519 }}
      ssh_port: ${{ secrets.PORT }}
