name: 'Manual Deploy'
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - staging

jobs:
  manual-deploy:
    name: '${{ github.event.inputs.environment }}:${{ github.ref_name }}'
    uses: ./.github/workflows/deploy-action.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      branch: ${{ github.ref }}
    secrets:
      ssh_host: ${{ secrets.SSH_HOST }}
      ssh_user: ${{ secrets.SSH_USER }}
      ssh_key_ed25519: ${{ secrets.SSH_KEY_ED25519 }}
      ssh_port: ${{ secrets.SSH_PORT }}

  # This is useful for conditional workflow_dispatch jobs
  # manual-deploy-staging:
  #   name: 'Deploy to Staging'
  #   if: ${{ github.event.inputs.environment == 'staging' }}
  #   uses: ./.github/workflows/deploy-action.yml
  #   with:
  #     environment: STAGING
  #     branch: ${{ github.ref }}
  #   secrets:
  #     ssh_host: ${{ secrets.SSH_HOST }}
  #     ssh_user: ${{ secrets.SSH_USER }}
  #     ssh_key_ed25519: ${{ secrets.SSH_KEY_ED25519 }}
  #     ssh_port: ${{ secrets.SSH_PORT }}
