name: 'Manual Deploy'
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - staging

jobs:
  manual-deploy-dev:
    name: 'Deploy to Dev'
    if: ${{ github.event.inputs.environment == 'dev' }}
    uses: ./.github/workflows/deploy-app-workflow.yml
    with:
      environment: DEV
      branch: ${{ github.ref }}
    secrets:
      ssh_host: ${{ secrets.HOST }}
      ssh_user: ${{ secrets.USERNAME }}
      ssh_key_ed25519: ${{ secrets.KEY_ED25519 }}
      ssh_port: ${{ secrets.PORT }}

  manual-deploy-staging:
    name: 'Deploy to Staging'
    if: ${{ github.event.inputs.environment == 'staging' }}
    uses: ./.github/workflows/deploy-app-workflow.yml
    with:
      environment: STAGING
      branch: ${{ github.ref }}
    secrets:
      ssh_host: ${{ secrets.STAGING_HOST }}
      ssh_user: ${{ secrets.USERNAME }}
      ssh_key_ed25519: ${{ secrets.STAGING_KEY_ED25519 }}
      ssh_port: ${{ secrets.PORT }}
