name: 'PR Tests'
on:
  pull_request:
    branches: [main, develop]

jobs:
  pr-lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.1

      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Run lint and type checks
        run: pnpm lint & pnpm check:types & wait

      - name: Run tests
        run: pnpm test -- --maxWorkers=4 --no-color --coverage=false --changedSince=origin/main
